<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AIO-2107" name="sanity.Mobile_VDL_Listing" tests="8" failures="0" timestamp="20 Feb 2017 04:27:29 GMT" time="128.194" errors="1">
  <testcase name="TC002_SortOption" time="28.203" classname="sanity.Mobile_VDL_Listing"/>
  <testcase name="TC003_Listing_SavetoPhone" time="26.748" classname="sanity.Mobile_VDL_Listing"/>
  <testcase name="TC004_Getquote" time="10.073" classname="sanity.Mobile_VDL_Listing"/>
  <testcase name="TC007_ListingVerifiedMark" time="6.705" classname="sanity.Mobile_VDL_Listing"/>
  <testcase name="US_API_City_selection" time="0.542" classname="sanity.Mobile_VDL_Listing">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at sanity.Mobile_VDL_Listing.US_API_City_selection(Mobile_VDL_Listing.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- US_API_City_selection -->
  <testcase name="TC001_Filterby" time="31.735" classname="sanity.Mobile_VDL_Listing"/>
  <testcase name="TC005_ListingProfile_ScoreMatch" time="14.376" classname="sanity.Mobile_VDL_Listing"/>
  <testcase name="TC006_ListingProfile_Review" time="9.812" classname="sanity.Mobile_VDL_Listing"/>
</testsuite> <!-- sanity.Mobile_VDL_Listing -->
